# Configuration file for the game
Title=Chopper Test
Version=0.1.0
Author=mblackman
Description=A simple test for my engine.
StartupScript=game.lua
DefaultScalingMode=nearest
DefaultWindowWidth=1920
DefaultWindowHeight=1080